version: '3'
services:
  ch_server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse:cached
      - ./setup/clickhouse/scripts:/docker-entrypoint-initdb.d:ro
      - ./setup/clickhouse/configs/users.xml:/etc/clickhouse-server/users.xml:ro
    restart: always
    hostname: clickhouse-server
    

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf